This is makeindex, version 2.15 [TeX Live 2013] (kpathsea + Thai support).
Scanning style file ./projectreport_eriksore.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file projectreport_eriksore.acn....done (1 entries accepted, 0 rejected).
Sorting entries...done (0 comparisons).
Generating output file projectreport_eriksore.acr....done (6 lines written, 0 warnings).
Output written in projectreport_eriksore.acr.
Transcript written in projectreport_eriksore.alg.
